import type { DatasetProfile } from '../types/api'
import { formatNumber } from '../utils/format'
import { Badge, EmptyState, SectionHeading, StatusMessage } from './Common'

export function ProfilePanel({ profile, loading, error, onRetry }: { profile: DatasetProfile | null; loading: boolean; error: string | null; onRetry: () => void }) {
  if (loading) return <div className="panel loading-state"><span className="spinner" aria-hidden="true" />Profiling dataset...</div>
  if (error) return <div className="panel"><StatusMessage title="Profile unavailable" detail={error} tone="error" /><button className="button button-secondary retry-button" type="button" onClick={onRetry}>Try again</button></div>
  if (!profile) return <EmptyState title="Profile not loaded" detail="Select a dataset to inspect its profile." />
  return <div className="profile-stack"><div className="metric-strip panel"><Metric label="Rows" value={formatNumber(profile.row_count)} /><Metric label="Columns" value={formatNumber(profile.column_count)} /><Metric label="Duplicates" value={formatNumber(profile.duplicate_row_count)} /><Metric label="Quality score" value={`${formatNumber(profile.quality.score)}/100`} accent={profile.quality.score >= 85 ? 'good' : profile.quality.score >= 60 ? 'warn' : 'bad'} /></div><section className="panel"><SectionHeading title="Data quality" detail={`${profile.quality.completeness_percentage}% complete · ${profile.quality.missing_cell_count} missing cells`} />{profile.quality.issues.length ? <div className="issue-list">{profile.quality.issues.map((issue, index) => <div className="issue-row" key={`${issue.code}-${index}`}><Badge value={issue.severity} tone={issue.severity} /><div><strong>{issue.message}</strong>{issue.column && <small>Column: {issue.column}</small>}</div></div>)}</div> : <StatusMessage title="No quality issues reported" tone="success" />}</section><section className="panel"><SectionHeading title="Column profile" detail="Detected types and statistical signals" /><div className="table-wrap"><table><thead><tr><th>Column</th><th>Type</th><th>Missing</th><th>Unique</th><th>Numeric statistics</th></tr></thead><tbody>{profile.columns.map((column) => <tr key={column.name}><td><strong>{column.name}</strong></td><td><span className="type-chip">{column.data_type}</span></td><td>{column.missing_count} <small>({column.missing_percentage}%)</small></td><td>{column.unique_count}</td><td>{column.numeric_statistics ? <span>{formatNumber(column.numeric_statistics.mean)} mean · {column.numeric_statistics.outlier_count} outliers ({column.numeric_statistics.outlier_percentage}%)</span> : '—'}</td></tr>)}</tbody></table></div></section></div>
}
function Metric({ label, value, accent }: { label: string; value: string; accent?: string }) { return <div className="metric"><span>{label}</span><strong className={accent ? `metric-${accent}` : ''}>{value}</strong></div> }
